# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Create zip file of artifacts
      run: |
        mkdir -p artifacts
        cp -r bin/Release/net9.0/* artifacts/
        zip -r "Automatic OSC Router.zip" artifacts/
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "Automatic OSC Router"
        path: "Automatic OSC Router.zip"
